print('----- range(3) -----')
print(range(3))
for x in range(3): print(x)
print('----- range(3, 10) -----')
print(range(3, 10))
for x in range(3, 10): print(x)
print('----- range(-3) -----')
print(range(-3))
for x in range(-3): print(x)
print('----- range(0,-3) -----')
print(range(0,-3))
for x in range(0,-3): print(x)
print('----- range(-3,0) -----')
print(range(-3,0))
for x in range(-3,0): print(x)
print('----- range(0,-3,-1) -----')
print(range(0,-3,-1))
for x in range(0,-3,-1): print(x)
