print(b'abc'.endswith(b'a'))
print(b'abc'.endswith(b'b'))
print(b'abc'.endswith(b'c'))
print(b'abc'.endswith(b'bc'))
print(b'abc'.endswith(b'abc'))
#print(b'aBc'.casefold().endswith((b'b', b'c'))) #AttributeError: 'bytes' object has no attribute 'casefold'
print()
print(b'abc'.startswith(b'a'))
print(b'abc'.startswith(b'b'))
print(b'abc'.startswith(b'c'))
print(b'abc'.startswith(b'bc'))
print(b'abc'.startswith(b'abc'))

print('\n')
b = bytearray(b'abc')
print(b.endswith(b'a'))
print(b.endswith(b'b'))
print(b.endswith(b'c'))
print(b.endswith(b'bc'))
print(b.endswith(b'abc'))
print()
print(b.startswith(b'a'))
print(b.startswith(b'b'))
print(b.startswith(b'c'))
print(b.startswith(b'bc'))
print(b.startswith(b'abc'))

