s = b'abc'; print(s.islower(), s)
s = b'Abc'; print(s.islower(), s)
s = b'ABC'; print(s.islower(), s)
s = b'123'; print(s.islower(), s)
s = b'(_)'; print(s.islower(), s)
s = b'(abc)'; print(s.islower(), s)
s = b'(aBc)'; print(s.islower(), s)

s = bytearray(b'abc'); print(s.islower(), s)
s = bytearray(b'Abc'); print(s.islower(), s)
s = bytearray(b'ABC'); print(s.islower(), s)
s = bytearray(b'123'); print(s.islower(), s)
s = bytearray(b'(_)'); print(s.islower(), s)
s = bytearray(b'(abc)'); print(s.islower(), s)
s = bytearray(b'(aBc)'); print(s.islower(), s)
