s = b'abc'; print(s.istitle(), s)
s = b'Abc'; print(s.istitle(), s)
s = b'aBc'; print(s.istitle(), s)
s = b'abC'; print(s.istitle(), s)
s = b'abc'; print(s.istitle(), s)
s = b'ABC'; print(s.istitle(), s)
s = b'abc'; print(s.capitalize().istitle(), s.capitalize())

s = bytearray(b'abc'); print(s.istitle(), s)
s = bytearray(b'Abc'); print(s.istitle(), s)
s = bytearray(b'aBc'); print(s.istitle(), s)
s = bytearray(b'abC'); print(s.istitle(), s)
s = bytearray(b'abc'); print(s.istitle(), s)
s = bytearray(b'ABC'); print(s.istitle(), s)
s = bytearray(b'abc'); print(s.capitalize().istitle(), s.capitalize())
